name: Deploy

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  # Deploy to production
  deploy-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Deploy using SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Navigate to project directory
            cd ${{ secrets.PROJECT_PATH }}
            
            # Pull latest changes
            git pull origin main
            
            # Update Docker Compose configuration
            docker-compose pull
            
            # Deploy with zero downtime
            docker-compose up -d --no-deps --build
            
            # Clean up old images
            docker image prune -af
            
            # Check deployment status
            docker-compose ps
          EOF
      
      - name: Verify deployment
        run: |
          echo "Waiting for services to start up..."
          sleep 30
          curl -f http://${{ secrets.DEPLOY_HOST }}/health || exit 1
          echo "Deployment verification successful!"
      
      - name: Send deployment notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_TITLE: Production Deployment
          SLACK_MESSAGE: "Trading Dashboard has been deployed to production 🚀"
          SLACK_COLOR: good